export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const CANCEL_GET_PRODUCTS = 'CANCEL_GET_PRODUCTS';
export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';
export const SET_LAST_REF_KEY = 'SET_LAST_REF_KEY';

export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const ADD_QTY_ITEM = 'ADD_QTY_ITEM';
export const MINUS_QTY_ITEM = 'MINUS_QTY_ITEM';

export const SET_CHECKOUT_SHIPPING_DETAILS = 'SET_CHECKOUT_SHIPPING_DETAILS';
export const SET_CHECKOUT_PAYMENT_DETAILS = 'SET_CHECKOUT_PAYMENT_DETAILS';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE';
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK';
export const SIGNIN_WITH_GITHUB = 'SIGNIN_WITH_GITHUB';
export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';
export const ON_AUTHSTATE_SUCCESS = 'ON_AUTHSTATE_SUCCESS';
export const ON_AUTHSTATE_FAIL = 'ON_AUTHSTATE_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_MIN_PRICE_FILTER = 'SET_MIN_PRICE_FILTER';
export const SET_MAX_PRICE_FILTER = 'SET_MAX_PRICE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const APPLY_FILTER = 'APPLY_FILTER';
export const CLEAR_RECENT_SEARCH = 'CLEAR_RECENT_SEARCH';
export const REMOVE_SELECTED_RECENT = 'REMOVE_SELECTED_RECENT';

export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const LOADING = 'LOADING';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';


//
export const ID = "ID";
export const ID_DETAIL = "ID_DETAIL";
export const SEARCH_RESULT = "SEARCH_RESULT";
export const SEARCH_RESULT_NULL = "SEARCH_RESULT_NULL";
export const SEARCH_BRAND = "SEARCH_BRAND";
export const CLICK_CATEGORY = "CLICK_CATEGORY";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const TOGGLE_FORM = "TOGGLE_FORM";
export const CLOSE_FORM = "CLOSE_FORM";
export const OPEN_FORM = "OPEN_FORM";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GETPRODUCT_DATABASE = "GETPRODUCT_DATABASE";
export const DELETE_CART = "DELETE_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const TOTAL_PRICE = "TOTAL_PRICE";
export const GETSTATE = "GETSTATE";
export const BILL_ID = "BILL_ID";
export const CART_ID = "CART_ID";
export const UPIMG_ID = "UPIMG_ID";
export const UPPRODUCT_ID = "UPPRODUCT_ID";
export const LOAD_PRODUCT_LIST = "LOAD_PRODUCT_LIST";
export const GETPRODUCT = "GETPRODUCT";
export const API_NEWEE_5000 = "https://api.newee.asia:5001";

//api
export const API_NEWEE_5001 = "https://api.newee.asia:5001";

export const API_NEWEE_6001 = "https://api.newee.asia:5001";

export const API_NEWEE_7001 = "https://api.newee.asia:5001";

export const API_TEST = "https://api.newee.asia:5001";
export const ADDTOCART = "ADDTOCART";
export const REMOVETOCART = "REMOVETOCART";
export const INCREASE_QUANTITY_SHOP = "INCREASE_QUANTITY_SHOP";
export const DECREASE_QUANTITY_SHOP = "DECREASE_QUANTITY_SHOP";
export const UPDATE_QUANTITY_SHOP = "UPDATE_QUANTITY_SHOP";
export const GET_ALL_PRODUCT_SHOP = "GET_ALL_PRODUCT_SHOP";
export const GET_NUMBER_CART_SHOP = "GET_NUMBER_CART_SHOP";
export const ADD_CART_SHOP = "ADD_CART_SHOP";
export const UPDATE_CART_SHOP = "UPDATE_CART_SHOP";
export const DELETE_CART_SHOP = "DELETE_CART_SHOP";
export const CLEAR_CART_SHOP = "CLEAR_CART_SHOP";
export const LOAD_CART_LIST = "LOAD_CART_LIST";
export const ID_PRODUCT = "ID_PRODUCT";
export const CHOOSE_STEP_1 = "CHOOSE_STEP_1";
export const CHOOSE_STEP_2 = "CHOOSE_STEP_2";
export const CHOOSE_STEP_3 = "CHOOSE_STEP_3";
export const CHOOSE_STEP_3_IMAGE = "CHOOSE_STEP_3_IMAGE";
export const DATA_LOGIN = "DATA_LOGIN";
export const NEWEE_LOGIN = "NEWEE_LOGIN";
export const ALL_PRODUCT = "ALL_PRODUCT";
export const BEST_PRODUCT = "BEST_PRODUCT";
export const CK_PRODUCT = "BEST_PRODUCT";
export const LOAD_ALL_PRODUCT_LIST = "LOAD_ALL_PRODUCT_LIST";
export const LOAD_ALL_PRODUCT_SOCIAL = "LOAD_ALL_PRODUCT_SOCIAL";

// FETCH PRODUCT NOT TOKEN

export const FETCH_PRODUCT_PUBLIC = "FETCH_PRODUCT_PUBLIC";

// 18-03-2022
export const CART_LOADING = "CART_LOADING";
export const CART_FAILURE = "CART_FAILURE";

// 30/03/2022
// Public
export const PRODUCT_GET_ALL = "PRODUCT_GET_ALL";
export const PRODUCT_GET_ALL_RELOAD = "PRODUCT_GET_ALL_RELOAD";
export const PRODUCT_GET_LIKE = "PRODUCT_GET_LIKE";
export const PRODUCT_GET_LIKE_CHANGE = "PRODUCT_GET_LIKE_CHANGE";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_GET_CATEGORY = "PRODUCT_GET_CATEGORY";

// Private
export const USER = "USER";
export const USER_INFO = "USER_INFO";
export const PRIVATE_ERROR = "PRIVATE_ERROR";
export const PRIVATE_CART_LOADING = "PRIVATE_CART_LOADING";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM ";
export const USER_LOGOUT = "USER_LOGOUT";
export const CLEAR_CART = "CLEAR_CART";
export const PRODUCT_LIKE_REMOVE = "PRODUCT_LIKE_REMOVE";
export const ON_SPINNERS = "ON_SPINNERS";
export const OFF_SPINNERS = "OFF_SPINNERS";
